### ISSUE TITLE
Segmentation fault(core dumped)? Could you give a example for how to use the source code?

### ISSUE THREAD

**Issue by pranerd** [zeyiwen/gpu-svm#13]
I use the git clone the source code and under the   gpu-svm directory make the code. Then I download the iris data from libsvm site, put it under the directory dataset/. Then according to the run.sh, use the command ./run.sh iris. Then it raise a error ./run.sh line 86 **# segmentation fault (core dumped)**  I hope there is a tutorial for how to using the source code.

**Comment by zeyiwen** [comment]
The problem is fixed. Please try "./run.sh iris" again. Thanks!

**Comment by pranerd** [comment]
I'm sorry, I git clone the code again and make it. then run it gain, it still has the problem.
it displays + ./bin/release/mascot -b 0 -o 0 -g 0.5 -c 100 -r 1 -e dataset/iris.scale.t dataset/iris.scale, then it raise error **./run.sh: line 86:  9415 Segmentation fault      (core dumped)**

**Comment by zeyiwen** [comment]
You may try other dataset, such as a1a. If you still get the same problem, I think it's the version issue.

What is the version of cuda and nvidia driver on your machine?

**Comment by pranerd** [comment]
I try the dataset of a1a, it still has the problem. I typed the command nvcc -V, the version of cuda in my linux server is **Cuda compilation tools, release 7.5, V7.5.17**.

**Comment by zeyiwen** [comment]
We've tested our code on about 10 machines including servers and desktops, but couldn't reproduce the Segmentation fault issue. Please make sure: 1. other GPU programs can run on your machine (I've some concern about your GPU driver); 2. you have our latest code, and make fresh executable file.

Moreover, you may try "make debug" and then run "./bin/debug/mascot -b 0 -o 0 -g 0.5 -c 100 -r 1 dataset/iris.scale"; and see if debug mode works.

**Comment by pranerd** [comment]
I follow your advices, try "make debug" and then run the script, the debug mode works.

**Comment by zeyiwen** [comment]
Sound good. Please note that debug mode is much slower than release mode.

I'd appreciate if you could find out a way for us to reproduce your problem, or if you could help us resolve it.

**Comment by pranerd** [comment]
I found that if the cuda version is release 8.0, V8.0.44, the ./run.sh is OK.

**Comment by zeyiwen** [comment]
Thank you for letting us know!
